#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CiclicaApp_DB")]
	public partial class conexionlinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public conexionlinqDataContext() : 
				base(global::Backend.Properties.Settings.Default.CiclicaApp_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_IngresarUsuario")]
		public int sp_IngresarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_NOMBRE", DbType="VarChar(200)")] string uSER_NOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_PRIMER_APELLIDO", DbType="VarChar(150)")] string uSER_PRIMER_APELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_SEGUNDO_APELLIDO", DbType="VarChar(150)")] string uSER_SEGUNDO_APELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_CORREO", DbType="VarChar(200)")] string uSER_CORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_CONTRASENA", DbType="VarChar(50)")] string uSER_CONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_NOMBRE, uSER_PRIMER_APELLIDO, uSER_SEGUNDO_APELLIDO, uSER_CORREO, uSER_CONTRASENA, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(5)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(6)));
			errorDescripcion = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
