<?xml version="1.0" encoding="utf-8"?><Database Name="CiclicaApp_DB" Class="conexionlinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=appciclicadb.database.windows.net;Initial Catalog=CiclicaApp_DB;User ID=admin01" SettingsObjectName="Backend.Properties.Settings" SettingsPropertyName="CiclicaApp_DBConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_IngresarUsuario" Method="sp_IngresarUsuario">
    <Parameter Name="USER_NOMBRE" Parameter="uSER_NOMBRE" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="USER_PRIMER_APELLIDO" Parameter="uSER_PRIMER_APELLIDO" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="USER_SEGUNDO_APELLIDO" Parameter="uSER_SEGUNDO_APELLIDO" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="USER_CORREO" Parameter="uSER_CORREO" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="USER_CONTRASENA" Parameter="uSER_CONTRASENA" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorDescripcion" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_LoginUsuario" Method="SP_LoginUsuario">
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Contrasena" Parameter="contrasena" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorDescripcion" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ObtenerSession" Method="sp_ObtenerSession">
    <Parameter Name="session" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorDescripcion" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <ElementType Name="sp_ObtenerSessionResult">
      <Column Name="SESSION_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SESSION_USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SESSION" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SESSION_FECHA_INICIO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SESSION_FECHA_FINAL" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SESSION_ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_IngresarSession" Method="sp_IngresarSession">
    <Parameter Name="SESSION_USER_ID" Parameter="sESSION_USER_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SESSION" Parameter="sESSION" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorDescripcion" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_CerrarSesionesAntiguas" Method="sp_CerrarSesionesAntiguas">
    <Parameter Name="SESSION" Parameter="sESSION" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorDescripcion" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_IngresarRegistroCicloMenstrual" Method="sp_IngresarRegistroCicloMenstrual">
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaInicioCiclo" Parameter="fechaInicioCiclo" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DuracionCiclo" Parameter="duracionCiclo" Type="System.Int32" DbType="Int" />
    <Parameter Name="DuracionMenstruacion" Parameter="duracionMenstruacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorDescripcion" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ObtenerAnticonceptivos" Method="sp_ObtenerAnticonceptivos">
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorDescripcion" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ANTI_CONCEP_ID" Parameter="aNTI_CONCEP_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ObtenerAnticonceptivosResult">
      <Column Name="ANTI_CONCEP_NOMBRE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ANTI_EFECTIVIDAD" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_MostrarHistorialAnticonceptivos" Method="sp_MostrarHistorialAnticonceptivos">
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorDescripcion" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_MostrarHistorialAnticonceptivosResult">
      <Column Name="ANTI_CONCEP_NOMBRE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOTIFI_START_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NOTIFI_FECHA_FINAL" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_MostrarConsejos" Method="sp_MostrarConsejos">
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorDescripcion" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_MostrarConsejosResult">
      <Column Name="CONSJ_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CONSJ_CONSEJO" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_InsertarNotificacion" Method="sp_InsertarNotificacion">
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorDescripcion" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ANTI_CONCEP_ID" Parameter="aNTI_CONCEP_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaHoraNotificacion" Parameter="fechaHoraNotificacion" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ActualizarNotificacion" Method="sp_ActualizarNotificacion">
    <Parameter Name="idReturn" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="errorDescripcion" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ANTI_CONCEP_ID" Parameter="aNTI_CONCEP_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>