#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CiclicaApp_DB")]
	public partial class conexionlinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public conexionlinqDataContext() : 
				base(global::Backend.Properties.Settings.Default.CiclicaApp_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexionlinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_IngresarUsuario")]
		public int sp_IngresarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_NOMBRE", DbType="VarChar(200)")] string uSER_NOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_PRIMER_APELLIDO", DbType="VarChar(150)")] string uSER_PRIMER_APELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_SEGUNDO_APELLIDO", DbType="VarChar(150)")] string uSER_SEGUNDO_APELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_CORREO", DbType="VarChar(200)")] string uSER_CORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_CONTRASENA", DbType="VarChar(50)")] string uSER_CONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_NOMBRE, uSER_PRIMER_APELLIDO, uSER_SEGUNDO_APELLIDO, uSER_CORREO, uSER_CONTRASENA, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(5)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(6)));
			errorDescripcion = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LoginUsuario")]
		public int SP_LoginUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(200)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(50)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo, contrasena, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			errorDescripcion = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ObtenerSession")]
		public ISingleResult<sp_ObtenerSessionResult> sp_ObtenerSession([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string session, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), session, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorDescripcion = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<sp_ObtenerSessionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_IngresarSession")]
		public int sp_IngresarSession([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESSION_USER_ID", DbType="Int")] System.Nullable<int> sESSION_USER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESSION", DbType="VarChar(MAX)")] string sESSION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESSION_USER_ID, sESSION, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			errorDescripcion = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CerrarSesionesAntiguas")]
		public int sp_CerrarSesionesAntiguas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESSION", DbType="VarChar(MAX)")] string sESSION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESSION, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(2)));
			errorDescripcion = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_IngresarRegistroCicloMenstrual")]
		public int sp_IngresarRegistroCicloMenstrual([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaInicioCiclo", DbType="Date")] System.Nullable<System.DateTime> fechaInicioCiclo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DuracionCiclo", DbType="Int")] System.Nullable<int> duracionCiclo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DuracionMenstruacion", DbType="Int")] System.Nullable<int> duracionMenstruacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID, fechaInicioCiclo, duracionCiclo, duracionMenstruacion, idReturn, errorId, errorDescripcion);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(4)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(5)));
			errorDescripcion = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_MostrarHistorialAnticonceptivos")]
		public ISingleResult<sp_MostrarHistorialAnticonceptivosResult> sp_MostrarHistorialAnticonceptivos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReturn, errorId, errorDescripcion, uSER_ID);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<sp_MostrarHistorialAnticonceptivosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_MostrarConsejos")]
		public ISingleResult<sp_MostrarConsejosResult> sp_MostrarConsejos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReturn, errorId, errorDescripcion, uSER_ID);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<sp_MostrarConsejosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ActualizarNotificacion")]
		public int sp_ActualizarNotificacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReturn, errorId, errorDescripcion, uSER_ID);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ObtenerAnticonceptivos")]
		public ISingleResult<sp_ObtenerAnticonceptivosResult> sp_ObtenerAnticonceptivos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReturn, errorId, errorDescripcion, uSER_ID);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<sp_ObtenerAnticonceptivosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarNotificacion")]
		public int sp_InsertarNotificacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> idReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> errorId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string errorDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ANTI_CONCEP_ID", DbType="Int")] System.Nullable<int> aNTI_CONCEP_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaNotifi", DbType="DateTime")] System.Nullable<System.DateTime> fechaNotifi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoraNotifi", DbType="DateTime")] System.Nullable<System.DateTime> horaNotifi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReturn, errorId, errorDescripcion, uSER_ID, aNTI_CONCEP_ID, fechaNotifi, horaNotifi);
			idReturn = ((System.Nullable<int>)(result.GetParameterValue(0)));
			errorId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			errorDescripcion = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_ObtenerSessionResult
	{
		
		private int _SESSION_ID;
		
		private int _SESSION_USER_ID;
		
		private string _SESSION;
		
		private System.Nullable<System.DateTime> _SESSION_FECHA_INICIO;
		
		private System.Nullable<System.DateTime> _SESSION_FECHA_FINAL;
		
		private System.Nullable<bool> _SESSION_ESTADO;
		
		public sp_ObtenerSessionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION_ID", DbType="Int NOT NULL")]
		public int SESSION_ID
		{
			get
			{
				return this._SESSION_ID;
			}
			set
			{
				if ((this._SESSION_ID != value))
				{
					this._SESSION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION_USER_ID", DbType="Int NOT NULL")]
		public int SESSION_USER_ID
		{
			get
			{
				return this._SESSION_USER_ID;
			}
			set
			{
				if ((this._SESSION_USER_ID != value))
				{
					this._SESSION_USER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SESSION
		{
			get
			{
				return this._SESSION;
			}
			set
			{
				if ((this._SESSION != value))
				{
					this._SESSION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION_FECHA_INICIO", DbType="DateTime")]
		public System.Nullable<System.DateTime> SESSION_FECHA_INICIO
		{
			get
			{
				return this._SESSION_FECHA_INICIO;
			}
			set
			{
				if ((this._SESSION_FECHA_INICIO != value))
				{
					this._SESSION_FECHA_INICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION_FECHA_FINAL", DbType="DateTime")]
		public System.Nullable<System.DateTime> SESSION_FECHA_FINAL
		{
			get
			{
				return this._SESSION_FECHA_FINAL;
			}
			set
			{
				if ((this._SESSION_FECHA_FINAL != value))
				{
					this._SESSION_FECHA_FINAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION_ESTADO", DbType="Bit")]
		public System.Nullable<bool> SESSION_ESTADO
		{
			get
			{
				return this._SESSION_ESTADO;
			}
			set
			{
				if ((this._SESSION_ESTADO != value))
				{
					this._SESSION_ESTADO = value;
				}
			}
		}
	}
	
	public partial class sp_MostrarHistorialAnticonceptivosResult
	{
		
		private string _ANTI_CONCEP_NOMBRE;
		
		private System.DateTime _NOTIFI_START_DATE;
		
		private System.Nullable<System.DateTime> _NOTIFI_FECHA_FINAL;
		
		public sp_MostrarHistorialAnticonceptivosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANTI_CONCEP_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ANTI_CONCEP_NOMBRE
		{
			get
			{
				return this._ANTI_CONCEP_NOMBRE;
			}
			set
			{
				if ((this._ANTI_CONCEP_NOMBRE != value))
				{
					this._ANTI_CONCEP_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTIFI_START_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime NOTIFI_START_DATE
		{
			get
			{
				return this._NOTIFI_START_DATE;
			}
			set
			{
				if ((this._NOTIFI_START_DATE != value))
				{
					this._NOTIFI_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTIFI_FECHA_FINAL", DbType="DateTime")]
		public System.Nullable<System.DateTime> NOTIFI_FECHA_FINAL
		{
			get
			{
				return this._NOTIFI_FECHA_FINAL;
			}
			set
			{
				if ((this._NOTIFI_FECHA_FINAL != value))
				{
					this._NOTIFI_FECHA_FINAL = value;
				}
			}
		}
	}
	
	public partial class sp_MostrarConsejosResult
	{
		
		private int _CONSJ_ID;
		
		private string _CONSJ_CONSEJO;
		
		public sp_MostrarConsejosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSJ_ID", DbType="Int NOT NULL")]
		public int CONSJ_ID
		{
			get
			{
				return this._CONSJ_ID;
			}
			set
			{
				if ((this._CONSJ_ID != value))
				{
					this._CONSJ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSJ_CONSEJO", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CONSJ_CONSEJO
		{
			get
			{
				return this._CONSJ_CONSEJO;
			}
			set
			{
				if ((this._CONSJ_CONSEJO != value))
				{
					this._CONSJ_CONSEJO = value;
				}
			}
		}
	}
	
	public partial class sp_ObtenerAnticonceptivosResult
	{
		
		private int _ANTI_CONCEP_ID;
		
		private string _ANTI_CONCEP_NOMBRE;
		
		private string _ANTI_EFECTIVIDAD;
		
		public sp_ObtenerAnticonceptivosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANTI_CONCEP_ID", DbType="Int NOT NULL")]
		public int ANTI_CONCEP_ID
		{
			get
			{
				return this._ANTI_CONCEP_ID;
			}
			set
			{
				if ((this._ANTI_CONCEP_ID != value))
				{
					this._ANTI_CONCEP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANTI_CONCEP_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ANTI_CONCEP_NOMBRE
		{
			get
			{
				return this._ANTI_CONCEP_NOMBRE;
			}
			set
			{
				if ((this._ANTI_CONCEP_NOMBRE != value))
				{
					this._ANTI_CONCEP_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANTI_EFECTIVIDAD", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ANTI_EFECTIVIDAD
		{
			get
			{
				return this._ANTI_EFECTIVIDAD;
			}
			set
			{
				if ((this._ANTI_EFECTIVIDAD != value))
				{
					this._ANTI_EFECTIVIDAD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
